### ISSUE TITLE
Add versioning

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/cnmem#3]
Can you add a version number to CNMeM? I want a lib with the version baked into the SONAME.

**Comment by jdemouth** [comment]
I've just added a version number and changed the CMakeLists.txt to create a proper SONAME.

I've also just tagged the version so you have release 1.0.0.

Let me know if you have what you need so I can close the issue. Thanks.

**Comment by lukeyeager** [comment]
Looks great, thanks!
